language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: chmod +x .travis-docker.sh && bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="tda_ocaml" CAML_VERSION="4.06"
  - PACKAGE="tda_ocaml" CAML_VERSION="4.07"
  - PACKAGE="tda_ocaml" CAML_VERSION="4.08"
  - PACKAGE="tda_ocaml" CAML_VERSION="4.09"
  - PACKAGE="tda_ocaml" CAML_VERSION="4.10"
  - PACKAGE="tda_ocaml" CAML_VERSION="4.11"